#!/usr/bin/env bash
# Configure Nginx to return "Hello World!" at the root URL

# Update the default Nginx configuration
sudo sed -i '/location \/ {/a \ \ \ \ \ \ \ \ echo "Hello World!";' /etc/nginx/sites-available/default

# Reload Nginx to apply the configuration changes
sudo service nginx reload

