#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Create a custom 404 error page
echo 'Ceci n'\''est pas une page' | sudo tee /usr/share/nginx/html/404_custom.html

# Update the Nginx default configuration to use the custom 404 page
sudo sed -i '/error_page 404 \/404.html;/a \ \ \ \ error_page 404 /404_custom.html;' /etc/nginx/sites-available/default

# Reload Nginx to apply the configuration changes
sudo service nginx reload

