#!/usr/bin/env bash
# This script connects to the server using SSH and a private key.

# Use the ssh command to connect to the server with the private key specified.
# Replace '52.86.171.34' with your actual server's IP address.
ssh -i ~/.ssh/school ubuntu@35.153.19.189
